
def my_custom_exception(job, exc_type, exc_value, traceback):
    return False